game:GetService("VirtualInputManager"):SendKeyEvent(true, "F9", false, game)
warn("This Script Has discontinued and won't work anymore")
wait(2)
warn("Join For Best Script Elemental: https://discord.gg/RcR4B6K4gr")
wait(1)
setclipboard("https://discord.gg/RcR4B6K4gr")
warn("This means I won't be compatible with Shadow Gui anymore.")
warn("For continued functionality, use Elemental instead.")
warn("Switch to Elemental for the best experience and up-to-date features.")
